services:
  productsv_db:
    image: postgres:16
    environment:
      POSTGRES_DB: product_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: product_service_db_password
    ports:
      - 5436:5432
    volumes:
      - productdb_vol:/var/lib/postgresql/data


volumes:
  productdb_vol: {}
