eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8585/realms/turkcell-p1-realm
  datasource:
    url: jdbc:postgresql://localhost:5436/product_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: product_service_db_password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9094

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9094
      bindings:
        orderCreated-in-0:
          destination: order-topic
          group: product-service
