spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eliffT/smart-order
          default-label: main
          search-paths: 
            - configurations/
            - configurations/{application}

server:
  port: 8787